name: App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: MobileDevOps/flutter-sdk-action@v1.0.0
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable 
          # Comma-separated list of target triples to install for this toolchain
          targets: aarch64-linux-android, armv7-linux-androideabi,i686-linux-android, x86_64-linux-android, x86_64-unknown-linux-gnu

      - name: check toolchain
        run: flutter --version && rustup show

      - name: install crates
        run: cargo install just cargo-expand

      - name: Install dependencies
        working-directory: ./esp_weather_app
        run: flutter pub get

      - name: Gen flutter_rust_bridge bindings
        working-directory: ./esp_weather_app
        run: just gen

      - name: build apk
        working-directory: ./esp_weather_app
        run: flutter build apk --release
