name: App

env:
  RUSTUP_HOME: /root/.rustup

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mnlphlp/flutter_rust_builder:1.3.1

    steps:
      - uses: actions/checkout@v3
      
      - name: rust cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./esp_weatehr_app/native/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: flutter cache
        uses: actions/cache@v3
        with:
          path: ./esp_weatehr_app/build
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-

      - name: check toolchain
        run: flutter --version && rustup show

      - name: Install flutter dependencies
        working-directory: ./esp_weather_app
        run: flutter pub get

      - name: Gen flutter_rust_bridge bindings
        working-directory: ./esp_weather_app
        run: just gen

      - name: build apk
        working-directory: ./esp_weather_app
        run: flutter build apk --release

      - name: rename apk
        run: mv esp_weather_app/build/app/outputs/flutter-apk/app-release.apk ./esp_weather.apk

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: esp_weather.apk
          # A file, directory or wildcard pattern that describes what to upload
          path: ./esp_weather.apk
